# Generated by Django 5.0.7 on 2024-08-02 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doorman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=194, verbose_name="full name"),
                ),
                (
                    "physic_person_register",
                    models.CharField(max_length=11, verbose_name="cpf"),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="telefone")),
                ("born_date", models.DateField(verbose_name="Data de nascimento")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Porteiro",),
                "verbose_name_plural": "Porteiros",
                "db_table": "doorman",
            },
        ),
    ]
