# Generated by Django 5.0.7 on 2024-08-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doormen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doorman",
            options={"verbose_name": "Doorman", "verbose_name_plural": "Doormen"},
        ),
        migrations.AlterField(
            model_name="doorman",
            name="born_date",
            field=models.DateField(verbose_name="Born Date"),
        ),
        migrations.AlterField(
            model_name="doorman",
            name="fullname",
            field=models.CharField(max_length=194, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="doorman",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="doorman",
            name="physic_person_register",
            field=models.CharField(
                max_length=11, verbose_name="Social Security Number / cpf"
            ),
        ),
    ]
