# Generated by Django 5.0.7 on 2024-08-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doormen", "0002_alter_doorman_options_alter_doorman_born_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doorman",
            old_name="physic_person_register",
            new_name="register_id",
        ),
    ]
