# Generated by Django 5.0.7 on 2024-08-02 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doormen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50, verbose_name="Full Name")),
                (
                    "person_identity",
                    models.CharField(max_length=11, verbose_name="Cpf"),
                ),
                ("born_date", models.DateField(verbose_name="born Date")),
                (
                    "house_number",
                    models.PositiveSmallIntegerField(verbose_name="House Number"),
                ),
                (
                    "vehicle_sign",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Vehicle Sign"
                    ),
                ),
                (
                    "arrived_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time Visitor Arrived"
                    ),
                ),
                (
                    "leave_hour",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time Visitor Left"
                    ),
                ),
                (
                    "hour_authorization",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Time Authorization happened",
                    ),
                ),
                (
                    "resident_responsible",
                    models.CharField(
                        blank=True,
                        max_length=194,
                        verbose_name="Resident who knows the visitor",
                    ),
                ),
                (
                    "registered_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="doormen.doorman",
                        verbose_name="Doorman who gives the visitor enter authorization",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Visitor",),
                "verbose_name_plural": "Visitors",
            },
        ),
    ]
