# Generated by Django 5.0.7 on 2024-08-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0002_alter_visitor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="person_identity",
            field=models.CharField(
                max_length=11, verbose_name="Social Security Number / cpf"
            ),
        ),
    ]
