# Generated by Django 5.0.7 on 2024-08-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0003_alter_visitor_person_identity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitor",
            old_name="registered_for",
            new_name="registered_by",
        ),
    ]
